http:
  port: "8081"
  host: "0.0.0.0"
  basePath: "/api/*"

external:
  api:
    host: "api.restful-api.dev"
    port: "443"
    protocol: "HTTPS"
    basePath: "/objects"

app:
  name: "MyAgentApp"
  version: "1.0.0"
  environment: "dev"